name: Publish Docker Image to Staging Prime Registry

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push-prime:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        
      - name: "Read vault secrets"
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials registry | STAGING_PRIME_REGISTRY ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials username | STAGING_PRIME_REGISTRY_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials password | STAGING_PRIME_REGISTRY_PASSWORD ;

        # This encapsulates: login, qemu, build/push
      - name: Build and push image to staging prime registry
        uses: rancher/ecm-distro-tools/actions/publish-image@575bb831c67edd950bfedb59d41dd127bd0005d6 # master
        with:
          image: rancher-ai-mcp
          tag: ${{ github.ref_name }}
          push-to-prime: true
          push-to-public: false
          prime-registry: ${{ env.STAGING_PRIME_REGISTRY }}
          prime-repo: rancher
          prime-username: ${{ env.STAGING_PRIME_REGISTRY_USERNAME }}
          prime-password: ${{ env.STAGING_PRIME_REGISTRY_PASSWORD }}
